import '~/styles/globals.css';

import { Fira_Mono } from 'next/font/google';
import { Toaster } from '~/components/ui/sonner';

const firaMono = Fira_Mono({
  weight: ['400', '500', '700'],
  variable: '--font-mono',
  subsets: ['latin-ext'],
});

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`font-mono ${firaMono.variable} h-screen overflow-hidden`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
